Add linters
fabianofrank/ruby-oop-library pull request #1
Opened 2022-05-17 19:06 UTC by fabianofrank

### Project requirements

1. Create class Person with the following:

- Instance vars: @id, @name, and @age.
- Constructor with name, age, and parent_permission as parameter. name and parent_permission are optional and have default values of "Unknown" and true.
- Getters for @id, @name, and @age.
- Setters for @name and @age.
- Private method is_of_age? that returns true if @age is greater or equal to 18 and false otherwise.
- Public method can_use_services? that returns true if person is of age or if they have permission from parents.

2. Create class Student with the following:

- Inherits from Person.
- Constructor extends parent's constructor by adding @classroom and a parameter for it.
- Method play_hooky that returns "¯\(ツ)/¯".

3. Create class Teacher with the following:

- Inherits from Person.
- Constructor extends parent's constructor by adding @specialization and a parameter for it.
- Override can_use_services? so it always returns true.

4. Each class should be saved in a separate file.

2022-05-17 19:32 UTC, TedLivist reviewed
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @fabianofrank,

Good job so far!
✔️ Classes are in different files
✔️ Set up of Person class
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly note that every section in the [Microverse README template](https://github.com/microverseinc/readme-template) is required, except for deployments, tests and live demo (where not applicable). Kindly add the **Built With** and **Prerequisites** sections
 
- [ ] For proper documentation, in your README kindly add detailed instructions on how to set up the project locally

_Check the comments under the review._

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-17 19:32 UTC, TedLivist commented on person.rb
> +  end
- [ ] This function can be refactored to prevent redundancy and have less code. Instead of using `age >= 18`, there is an `age_of?` function - use it here. And instead of `self.parent_permission = true`, you can use the `@parent_permission` instance variable instead.

  You should have something like this:
  ```
  def can_use_services?
    age_of? || @parent_permission
  end
  ```

2022-05-17 19:32 UTC, TedLivist commented on student.rb
> +class Student < Person
- [ ] You need to import the Person class in this file for this inheritance to work. Kindly do that using `require_relative`, as per Ruby convention.

2022-05-17 19:32 UTC, TedLivist commented on student.rb
> +  end
- [ ] You need to properly add the rest of the parameters (`age`, `name` `parent_permission`) in the initialize method here as we have them in the Person class for this constructor to function properly.

- [ ] You need to pass those parameters to the parent class using the `super()` method.

  In the end you should have something like this:
  ```
  def initialize(classroom, age, name = "Unknown", parent_permission: false)
    super(age, name, parent_permission: parent_permission)
    @classroom = classroom
  end
  ```

2022-05-17 19:32 UTC, TedLivist commented on teacher.rb
> +class Teacher < Person
- [ ] Kindly ensure you import the Person class in this file for the inheritance to work.

2022-05-17 19:32 UTC, TedLivist commented on teacher.rb
> +  end
- [ ] Kindly add the rest of the parameters as demonstrated above.

2022-05-17 19:32 UTC, TedLivist commented on person.rb
> +  attr_reader :id
- [ ] **[OPTIONAL]** For better organization, I would recommend you move this declaration to the top of the class.

2022-05-17 20:56 UTC, medaminedev66 requested changes
Hi @fabianofrank 😃,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- There are no linter errors ✔️
- You have a descriptive PR ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-17 20:56 UTC, medaminedev66 commented on teacher.rb
> +class Teacher < Person
- [ ] As requested by the previous reviewer, Kindly import the `Person` class to `teacher.rb` file. `Person` is still undefined in this file.

2022-05-17 20:56 UTC, medaminedev66 commented on person.rb
> +  end
- [ ] Following the DRY and KISS rules, it would be better to avoid redundancy and have less code. Kindly work on the changes that were required by the previous reviewer.

2022-05-17 20:56 UTC, medaminedev66 commented on student.rb
> +class Student < Person
- [ ] As requested by the previous reviewer, Kindly import the `Person` class to `student.rb` file. Person is still undefined in this file.

2022-05-17 20:56 UTC, medaminedev66 commented on student.rb
> +  end
- [ ] You need to properly add the rest of the parameters (age, name parent_permission) in the initialize method here as we have them in the Person class for this constructor to function properly. Please implement the changes requested by the previous reviewer.

2022-05-17 20:56 UTC, medaminedev66 commented on teacher.rb
> +  end
- [ ] You need to properly add the rest of the parameters (age, name parent_permission) in the initialize method here as we have them in the Person class for this constructor to function properly. Please implement the changes requested by the previous reviewer.

2022-05-17 20:56 UTC, medaminedev66 commented on README.md
[OPTIONAL] The `MIT link` and `issues page link` in the README file are broken. I would highly recommend fixing those sections to make README professional.

2022-05-18 00:18 UTC, rotimiazeez approved these changes
# Hi @fabianofrank 👍, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-18 01:34 UTC, merged