Add Decoratos
fabianofrank/ruby-oop-library pull request #2
Opened 2022-05-18 16:55 UTC by fabianofrank

### Project requirements

- Check the usage of Decorator pattern in Ruby
- Think about how you can use two decorators in order to capitalize and trim people's names.
- In the following steps you will get instructions for implementing the Decorator design pattern for this case.

2022-05-18 17:37 UTC, Meltrust requested changes
Hi @fabianofrank,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- Nice first implementation✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-18 17:37 UTC, Meltrust commented on nameable.rb
> +    raise NotImplementedError
- [ ] OPTIONAL:  It would be better if you specify the cause of the error like this:

```ruby
raise NotImplementedError, "#{self.class} has not implemented method '#{__method__}'"
```

2022-05-18 17:37 UTC, Meltrust commented on trimmer_decorator.rb
> +    @nameble.correct_name.length >= 10 ? @nameable.correct_name.slice!(0..10) : @nameable.correct_name
- [ ] You have a typo on "@nameble" which should be "@nameable".  Kindly correct this one.

2022-05-18 17:37 UTC, Meltrust commented on person.rb
> +require_relative './nameable'
- [ ] OPTIONAL: After making all the changes, I recommend you test if the project works like this:

```ruby

# adding this to the end of person.rb, just for the test:

person = Person.new(22, 'maximilianus')
puts person.correct_name
capitalized_person = CapitalizeDecorator.new(person)
puts capitalized_person.correct_name
capitalized_trimmed_person = TrimmerDecorator.new(capitalized_person)
puts capitalized_trimmed_person.correct_name

```

Then, on your terminal run `ruby person.rb`

This should appear on your terminal:

![image](https://user-images.githubusercontent.com/57421823/169106204-32488b83-1730-499c-aa02-b651536e32aa.png)


This is how I tested and debugged it.

### After you are sure all works, delete this test code and resend it for review.

I hope this is helpful 💪

2022-05-18 18:56 UTC, fabianofrank commented on person.rb
> +require_relative './nameable'
I only had to add to add the other requires for it to work.

2022-05-18 18:58 UTC, merged

2022-05-19 07:54 UTC, Meltrust commented on person.rb
> +require_relative './nameable'
Hey @fabianofrank, this last review comment was marked as optional.   I added it just to help you test and debug the project, but it's not required.  Happy coding! 💪